### ISSUE TITLE
Installing has_versioning as a plugin breaks Rails application

### ISSUE THREAD

**Issue by cjk** [kkurach/has_versioning#1]
I wanted to try out has_versioning as it sounds very promising from it's description.

So I installed it as a plugin.

But as soon as I've done that, without any other modifications yet on my models, my application started breaking in many ways.

I got errors like "undefined method `real_id' for #Class:0x2b772b6acb38" and others.

I'm using Rails 2.3.4

I'm using standard AR naming conventions.

Is has_versioning supposed to break an application after being installed and (not yet) configured.

Please let me know if you need further information.

Thanks,
Claus

**Comment by cyberkni** [comment]
Sorry to hear it blew up your app. It really shouldn't be blowing up your Rails app..

A stack trace would be handy to track down where/how its getting engaged before you are ready to use it.

**Comment by ajescudero** [comment]
I was about to install it as plugin ...

**Comment by cjk** [comment]
Sorry, can't provide a stack-trace since I switched to another versioning-solution. But for anyone having similar issues should try to install this (or any other plugin that is) as a gem instead. Load order might be the culprit. Actually I think has_versioning itself might not have caused the problem, but other plugins.

**Comment by merlagautham** [comment]
We too are facing the same problem. we are using Rails 2.3.5

Here is the stack trace
undefined method `real_id' for #Class:0xb6eefb68

/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:1959:in `method_missing_without_paginate'
/media/DATA/new_cp/vendor/plugins/will_paginate/lib/will_paginate/finder.rb:170:in`method_missing'
/media/DATA/new_cp/vendor/plugins/has_versioning/lib/has_versioning.rb:647:in `find_target'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations/association_proxy.rb:239:in`load_target'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations/association_proxy.rb:112:in `reload'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations.rb:1250:in`organization'
